[package]
name = "apply-nix-settings"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
publish = false
license = "CC0-1.0"
autobins = false

[[bin]]
name = "apply-nix-settings"
path = "src/main.rs"

[[bin]]
name = "apply-nix-settings-test-fixture"
path = "src/bin/apply-nix-settings-test-fixture.rs"
required-features = ["test-fixture"]

[features]
test-fixture = []

[dependencies]
libc = "0.2"
similar = "2.7"
tempfile = "3.23"
